/* Resource Datei Indizes fÅr BUBBLE */

#define DIALOG_BUBBLE    0   /* Formular/Dialog */
#define BLINK_COUNT      4   /* FTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ON        6   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_OFF       7   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_L   10  /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_CONTROL   11  /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ALTERNATE 12  /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_R   13  /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_SAVE      15  /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_CANCEL    16  /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_OK        17  /* BUTTON in Baum DIALOG_BUBBLE */

#define BUBBLES          1   /* Formular/Dialog */
#define BUBBLE_TAIL_BR   1   /* ICON in Baum BUBBLES */
#define BUBBLE_TAIL_BL   2   /* ICON in Baum BUBBLES */
#define BUBBLE_TAIL_TR   3   /* ICON in Baum BUBBLES */
#define BUBBLE_TAIL_TL   4   /* ICON in Baum BUBBLES */
