/* Resource Datei Indizes fÅr BUBBLE */

#define DIALOG_BUBBLE    0   /* Formular/Dialog */
#define BUTTON_OK        1   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_CANCEL    2   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_SAVE      3   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_R   4   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ALTERNATE 5   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_CONTROL   6   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_L   7   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ON        10  /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_OFF       11  /* BUTTON in Baum DIALOG_BUBBLE */

#define BUBBLES          1   /* Formular/Dialog */
#define BUBBLE_TAIL_BR   1   /* ICON in Baum BUBBLES */
#define BUBBLE_TAIL_BL   2   /* ICON in Baum BUBBLES */
#define BUTTON_TAIL_TR   3   /* ICON in Baum BUBBLES */
#define BUTTON_TAIL_TL   4   /* ICON in Baum BUBBLES */
