/* Resource Datei Indizes fÅr BUBBLE */

#define DIALOG_BUBBLE    0   /* Formular/Dialog */
#define BUTTON_OK        1   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_CANCEL    2   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_SAVE      3   /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_R   4   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ALTERNATE 5   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_CONTROL   6   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_SHIFT_L   7   /* BOXTEXT in Baum DIALOG_BUBBLE */
#define BUTTON_ON        10  /* BUTTON in Baum DIALOG_BUBBLE */
#define BUTTON_OFF       11  /* BUTTON in Baum DIALOG_BUBBLE */
